root = "."

[build]
cmd = "go build -o ./tmp/api ./cmd/api"
entrypoint = ["./tmp/api"]
include_ext = ["go", "toml", "env", "yaml", "yml"]
exclude_dir = ["tmp", "data", "bin", ".git"]
include_dir = ["cmd", "internal", "db", "api"]
delay = 1000

[log]
time = true
